name: Convert and Push Presentation

on:
  push:
    branches:
      - main

jobs:
  Convert:
    # strategy:
    #   matrix:
    #     format: [pptx, html]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install Marp CLI
        run: npm install -g @marp-team/marp-cli
      - name: Convert
        # run: marp --${{matrix.format}} marp-test.md
        run: marp --pptx marp-test.md
      - name: check
        run: ls

  Release:
    runs-on: ubuntu-latest
    needs: Convert
    steps:
      - uses: actions/checkout@v2
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
