name: Convert and Push Presentation

on:
  push:
    branches:
      - main

jobs:
  Convert:
    # strategy:
    #   matrix:
    #     format: [pptx, html]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install Marp CLI
        run: npm install -g @marp-team/marp-cli
      - name: Convert
        # run: marp --${{matrix.format}} marp-test.md
        run: marp --pptx marp-test.md
      - name: check
        run: ls

  Push:
    runs-on: ubuntu-latest
    needs: Convert
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/liatrio/marp-deckset-conversion:latest
